name: Pipeline CI/CD

on: [push, pull_request]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-mock

    - name: Ejecutar pruebas
      run: |
        echo "Ejecutando pruebas con Pytest..."
        pytest tests

    - name: Construir imagen Docker
      run: |
        COMMIT_HASH=$(git rev-parse --short HEAD)
        docker build -t myuser/myapp:latest -t myuser/myapp:$COMMIT_HASH .

    - name: Iniciar sesión en DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Publicar imagen
      run: |
        COMMIT_HASH=$(git rev-parse --short HEAD)
        docker push myuser/myapp:$COMMIT_HASH
        docker push myuser/myapp:latest
